# Keep acmsec.mst.edu up to date with master.
name: Continuous Deployment

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  Continuous-Deployment:
    runs-on: self-hosted

    steps:
      - name: Sync master branch to webserver
        uses: garygrossgarten/github-action-ssh@v0.6.4
        with:
          # git pull from master; ensure installed node packages are up to date with package.json; restart node services
          command: pushd /var/www/acmsec.mst.edu && git checkout master && git pull && pushd node && npm install && pm2 restart contentProvide & pm2 restart emailLists
          host: ${{ secrets.HOST }}
          username: ctf-admin
          privateKey: ${{ secrets.PRIVATE_KEY }}
